include: package:lints/recommended.yaml

analyzer:
  exclude:
    # Generated code (build_runner output).
    - "**/*.g.dart"
    - "**/*.freezed.dart"

formatter:
  page_width: 120

linter:
  rules:
    directives_ordering: true
    sort_pub_dependencies: true
